<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ActivityLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('activity_logs')->delete();
        
        \DB::table('activity_logs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 1,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":1,"name":"Jerry Tizon","email":"jgtizon@tesda.gov.ph","username":"Superadmin","password":"$2y$10$csmg.1nhdUOkH4Dbevz6bOBTY5h7KWd5gtfoMP5ULozs\\/uIlXnsri","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:47',
                'updated_at' => '2022-12-20 20:48:47',
            ),
            1 => 
            array (
                'id' => 2,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 2,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":1,"name":"Romelmar Alejandrino","email":"romelmar.alejandrino@gmail.com","username":"Administrator","password":"$2y$10$Wfkvn3\\/vvZajWtugcrwmOub3x2deUouxfJG8AV9SR47rS7hwRDAvW","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:47',
                'updated_at' => '2022-12-20 20:48:47',
            ),
            2 => 
            array (
                'id' => 3,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 3,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":2,"name":"Cecilia Burdeos","email":"ccburdeos@tesda.gov.ph","username":"Rod-chief","password":"$2y$10$2oBl49Xbt4hhmsJ.mItv3.WUGok9HfPHeXnNAieDfuAiSCA.JzF6q","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:47',
                'updated_at' => '2022-12-20 20:48:47',
            ),
            3 => 
            array (
                'id' => 4,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 4,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":2,"name":"Ellen Elio","email":"etelio@tesda.gov.ph","username":"Rod-ellen","password":"$2y$10$jksQ.9uJHgon6tL4IEHu0uSgP8b2cfL3D5r8AD.thYVbZ16E2wema","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:47',
                'updated_at' => '2022-12-20 20:48:47',
            ),
            4 => 
            array (
                'id' => 5,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 5,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":2,"name":"Ma. Joji Ann Pagtolon-an","email":"mjap@tesda.gov.ph","username":"Rod1","password":"$2y$10$3nx0yEwijmN8FL9T0KTUMO\\/iKQhKY7Y.ppALm6aZlQ4grQJGs2QH2","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:48',
                'updated_at' => '2022-12-20 20:48:48',
            ),
            5 => 
            array (
                'id' => 6,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 6,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":2,"name":"Maria Liba Celestial","email":"mlc@tesda.gov.ph","username":"Rod2","password":"$2y$10$ks50l8dz7wFQgVask4JnHellcbRDgsSlHYKV13RyiYhRZV\\/BfG01.","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:48',
                'updated_at' => '2022-12-20 20:48:48',
            ),
            6 => 
            array (
                'id' => 7,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 7,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":2,"name":"Mia Medicielo","email":"mia@tesda.gov.ph","username":"Rod3","password":"$2y$10$H5gUELTTjbU8DJUbFym4M.lvF0pee0xApxFo67yVN2VznJJ9e2NCe","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:48',
                'updated_at' => '2022-12-20 20:48:48',
            ),
            7 => 
            array (
                'id' => 8,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 8,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":2,"name":"Roger Esporas","email":"resporas@tesda.gov.ph","username":"Rod4","password":"$2y$10$4cFVHiWxADuLY8NjVVsQKO8YyO3VWaB646trYjYpOydLwDLGjgpS6","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:48',
                'updated_at' => '2022-12-20 20:48:48',
            ),
            8 => 
            array (
                'id' => 9,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 9,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":2,"name":"Bernadette Puertas","email":"bpuertas@tesda.gov.ph","username":"Rod5","password":"$2y$10$PWesO591OLZBD2GtrTZ7h.v9AfHvRsgsKJR\\/.7iugdTxane3oa1za","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:48',
                'updated_at' => '2022-12-20 20:48:48',
            ),
            9 => 
            array (
                'id' => 10,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 10,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":2,"name":"Christie Ann Corcino","email":"ccorcino@tesda.gov.ph","username":"Rod6","password":"$2y$10$VtcTqx6zsOUmriVcNqLiQOPGHuROC\\/r7NDYQbgrSgMoLOKL3hySMC","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:48',
                'updated_at' => '2022-12-20 20:48:48',
            ),
            10 => 
            array (
                'id' => 11,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 11,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":2,"name":"Jenny Seculles","email":"jseculles@tesda.gov.ph","username":"Rod7","password":"$2y$10$jONUiaT0qQVJ.b5mso6xMOmzb8ubpbTkCaoOlZHzaM2MA5k9EAd2e","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:48',
                'updated_at' => '2022-12-20 20:48:48',
            ),
            11 => 
            array (
                'id' => 12,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 12,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Porferio Celestial","email":"pcelestial@tesda.gov.ph","username":"Rtci-chief","password":"$2y$10$XnIncsbZS8.G9\\/Gr.88jROB1iBCHh2fQ3fcopjb0\\/xE9kaooaYVj6","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:48',
                'updated_at' => '2022-12-20 20:48:48',
            ),
            12 => 
            array (
                'id' => 13,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 13,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Donnabelle Sollesta","email":"dsollesta@tesda.gov.ph","username":"Rtci1","password":"$2y$10$Xctipd7bQN94xhxJHYq32umBPxEGIEAOp2vl3fepP7KgQRwwd2Lh6","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:48',
                'updated_at' => '2022-12-20 20:48:48',
            ),
            13 => 
            array (
                'id' => 14,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 14,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Ma. Juna Sarroza","email":"jsarroza@tesda.gov.ph","username":"Rtci2","password":"$2y$10$7TGF9AgV0R8d\\/9iJmIiNje2\\/OM5ilvEyN3nb\\/A8rdb3Hm90QhBdtW","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:49',
                'updated_at' => '2022-12-20 20:48:49',
            ),
            14 => 
            array (
                'id' => 15,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 15,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Joel Lopez","email":"rtci3@tesda.gov.ph","username":"Rtci3","password":"$2y$10$ZSbGwKHxP8slsoToZIihc.jIsrPUmE4dwo1HZRMlcrxhFs8.1tcym","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:49',
                'updated_at' => '2022-12-20 20:48:49',
            ),
            15 => 
            array (
                'id' => 16,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 16,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Vincent Nu\\u00f1al","email":"rtci4@tesda.gov.ph","username":"Rtci4","password":"$2y$10$nDjtwJ8OG6OorCO4BZW55OHE7Us8wJdK2TWLmvH3yynVzOBT.w3TW","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:49',
                'updated_at' => '2022-12-20 20:48:49',
            ),
            16 => 
            array (
                'id' => 17,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 17,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Ulysses Cortez Jr.","email":"rtci5@tesda.gov.ph","username":"Rtci5","password":"$2y$10$xKUA5hoqlo\\/lf1QXKee8mutXQuZNhqfSq8pe3F2b1u4NQRIEtzGO6","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:49',
                'updated_at' => '2022-12-20 20:48:49',
            ),
            17 => 
            array (
                'id' => 18,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 18,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"John Laurence Garanganao","email":"rtci6@tesda.gov.ph","username":"Rtci6","password":"$2y$10$RlJyBdE34YUpNNAMY6HqN.HCjrb5oRmmYG8kOzKbANH.sLnlyTTDW","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:49',
                'updated_at' => '2022-12-20 20:48:49',
            ),
            18 => 
            array (
                'id' => 19,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 19,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Fritz Pedregosa","email":"rtci7@tesda.gov.ph","username":"Rtci7","password":"$2y$10$94XLyQcn\\/zPjvo2xmas\\/k.6Ff1.syhrPYze3g4LiEw0ZmXEIdtiVm","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:49',
                'updated_at' => '2022-12-20 20:48:49',
            ),
            19 => 
            array (
                'id' => 20,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 20,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Leslie Ann Lagrada","email":"rtci8@tesda.gov.ph","username":"Rtci8","password":"$2y$10$fRN9suIMJ7mbpxoRE4whNu.uGn\\/tK3X7914dasWQmX2EtxPy.rrOi","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:49',
                'updated_at' => '2022-12-20 20:48:49',
            ),
            20 => 
            array (
                'id' => 21,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 21,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Liezl Echano","email":"rtci9@tesda.gov.ph","username":"Rtci9","password":"$2y$10$wwZkTtnhyNBc8mZkEriWjuxuH6jPRIgNPL4UT7s7vsY1ou3qzv4wK","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:49',
                'updated_at' => '2022-12-20 20:48:49',
            ),
            21 => 
            array (
                'id' => 22,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 22,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"KC Jane De la Torre","email":"rtci10@tesda.gov.ph","username":"Rtci10","password":"$2y$10$qcZBzIjDHCoVQcEAqpSqBOn\\/.9l31m9\\/J2wedEGO8W0aKVIoICtvW","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:49',
                'updated_at' => '2022-12-20 20:48:49',
            ),
            22 => 
            array (
                'id' => 23,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 23,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Lory Guile\\u00f1o","email":"rtci11@tesda.gov.ph","username":"Rtci11","password":"$2y$10$826qkcXhIf6gFX2qJ7zNmuSEku4\\/0ZwgcIIAW8X5yuUIH5xekTDx2","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:50',
                'updated_at' => '2022-12-20 20:48:50',
            ),
            23 => 
            array (
                'id' => 24,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 24,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Francis Correa","email":"rtci12@tesda.gov.ph","username":"Rtci12","password":"$2y$10$HE8ZtGVadFB5zn52JtZMKejJu9eXoFEu3GBJbowUjmO4OVnUzfbru","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:50',
                'updated_at' => '2022-12-20 20:48:50',
            ),
            24 => 
            array (
                'id' => 25,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 25,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":7,"name":"Susan Brendia","email":"rtci13@tesda.gov.ph","username":"Rtci13","password":"$2y$10$uB8CfD9WVqk1S.QksSHtcuZN3kuq5Ufaaj5a4aNB3EZLJ.puDeEsq","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:50',
                'updated_at' => '2022-12-20 20:48:50',
            ),
            25 => 
            array (
                'id' => 26,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 26,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"Ma. Mabel Biyo","email":"mmsbiyo@tesda.gov.ph","username":"Fasd-chief","password":"$2y$10$uRrAYr8YWuvMtLXmqyGd3uKC7W5dgXiU4.bA7ki.HKQq3BDDQxk0m","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:50',
                'updated_at' => '2022-12-20 20:48:50',
            ),
            26 => 
            array (
                'id' => 27,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 27,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"Arman Marbebe","email":"fasd1@tesda.gov.ph","username":"Fasd1","password":"$2y$10$fy8eEopWlKqfwyqbS.LsR.0S9us3unUd154EeFl0DOt9arFwMYwLe","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:50',
                'updated_at' => '2022-12-20 20:48:50',
            ),
            27 => 
            array (
                'id' => 28,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 28,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"Alva May Dollete","email":"fasd2@tesda.gov.ph","username":"Fasd2","password":"$2y$10$PX6CDuIZZwcG0VK9tpjZhOt\\/LwlwETmruEFtpqOFLGx5sXE.lSxzG","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:50',
                'updated_at' => '2022-12-20 20:48:50',
            ),
            28 => 
            array (
                'id' => 29,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 29,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"Jielcy Galas","email":"fasd3@tesda.gov.ph","username":"Fasd3","password":"$2y$10$V3VAf46CynlOuv1QuvaQz.u3DYWd4d\\/Ya9LW.uCXAd2IGQo5H\\/Dx6","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:50',
                'updated_at' => '2022-12-20 20:48:50',
            ),
            29 => 
            array (
                'id' => 30,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 30,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"Rogelyn Balberde","email":"fasd4@tesda.gov.ph","username":"Fasd4","password":"$2y$10$xm8SMewAz4eppXPhB9xqROP5pfCRzRd7fPxsCLMpv6juFZe5mfGCS","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:50',
                'updated_at' => '2022-12-20 20:48:50',
            ),
            30 => 
            array (
                'id' => 31,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 31,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"Yunny Sumanghid","email":"fasd5@tesda.gov.ph","username":"Fasd5","password":"$2y$10$mXSxIi7.6bAW1qFxgCrJ5.2JgdJ8UKZcb3ImDWOqlpIw4AM1su5bm","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:50',
                'updated_at' => '2022-12-20 20:48:50',
            ),
            31 => 
            array (
                'id' => 32,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 32,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"June Lyn Debil","email":"fasd6@tesda.gov.ph","username":"Fasd6","password":"$2y$10$iHztjuXl\\/7EjJ5OYF.eD0eV08IMtMRQ7sZ1U69NfIo7gvcY54HpKO","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:51',
                'updated_at' => '2022-12-20 20:48:51',
            ),
            32 => 
            array (
                'id' => 33,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 33,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"Edgar Porras","email":"fasd7@tesda.gov.ph","username":"Fasd7","password":"$2y$10$8155QOzL1VGIcV8KOR3N.eUvkOOnzT7ch2UK4g.dTpqXtI\\/Y.UtXW","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:51',
                'updated_at' => '2022-12-20 20:48:51',
            ),
            33 => 
            array (
                'id' => 34,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 34,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"Janine Mae Calaguing","email":"jmacalaguing@tesda.gov.ph","username":"Hrmo","password":"$2y$10$q0wUOIidD8qmqDo4atmExeKzayF2GA8zAFm8OcqjrmNmWr5rSeGZy","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:51',
                'updated_at' => '2022-12-20 20:48:51',
            ),
            34 => 
            array (
                'id' => 35,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 35,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":3,"name":"Rodgen Pagtolon-an","email":"recordsfasd@gmail.com","username":"Records","password":"$2y$10$WfH3S12IfSXaRC5YU68t5eyiBzjt56QnfP3ehR\\/xZ7LnQhrcJ7pty","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:51',
                'updated_at' => '2022-12-20 20:48:51',
            ),
            35 => 
            array (
                'id' => 36,
                'log_name' => 'User',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 36,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":{"role_id":null,"office_id":1,"division_id":1,"name":"return-clerk","email":"return@app.com","username":"Return-clerk","password":"$2y$10$78vw2nWp62dwzPtTDVGyAOAttqGx7SNTWcjIJrCQsSGXFxl9FUJPO","designation":null,"file_path":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:48:51',
                'updated_at' => '2022-12-20 20:48:51',
            ),
            36 => 
            array (
                'id' => 37,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 28,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            37 => 
            array (
                'id' => 38,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 9,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            38 => 
            array (
                'id' => 39,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 3,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            39 => 
            array (
                'id' => 40,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 4,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            40 => 
            array (
                'id' => 41,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 29,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            41 => 
            array (
                'id' => 42,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 1,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            42 => 
            array (
                'id' => 43,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 32,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            43 => 
            array (
                'id' => 44,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 34,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            44 => 
            array (
                'id' => 45,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 11,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            45 => 
            array (
                'id' => 46,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 20,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            46 => 
            array (
                'id' => 47,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 23,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            47 => 
            array (
                'id' => 48,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 21,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            48 => 
            array (
                'id' => 49,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 5,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            49 => 
            array (
                'id' => 50,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 14,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            50 => 
            array (
                'id' => 51,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 6,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            51 => 
            array (
                'id' => 52,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 12,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            52 => 
            array (
                'id' => 53,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 8,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            53 => 
            array (
                'id' => 54,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 30,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            54 => 
            array (
                'id' => 55,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 17,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            55 => 
            array (
                'id' => 56,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 16,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            56 => 
            array (
                'id' => 57,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 31,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes":[],"old":[]}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:56:42',
                'updated_at' => '2022-12-20 20:56:42',
            ),
            57 => 
            array (
                'id' => 58,
                'log_name' => 'Document',
                'description' => 'created',
                'subject_type' => 'App\\Models\\Document',
                'event' => 'created',
                'subject_id' => 1,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 35,
                'properties' => '{"attributes":{"doc_number":null,"memo_number":null,"origin_id":3,"mor_id":1,"doctype_id":1,"user_id":35,"status":0,"date_received":"2022-12-20","deadline":"2022-12-23","control_number":null,"subject":"test 1","updated_at":"2022-12-20T12:58:56.000000Z"}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:58:56',
                'updated_at' => '2022-12-20 20:58:56',
            ),
            58 => 
            array (
                'id' => 59,
                'log_name' => 'Document',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\Document',
                'event' => 'updated',
                'subject_id' => 1,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 35,
                'properties' => '{"attributes":{"doc_number":"TN-2022-12-20-0001","origin_id":3,"mor_id":1,"doctype_id":1,"user_id":35,"status":0,"date_received":"2022-12-20","deadline":"2022-12-23","subject":"test 1","updated_at":"2022-12-20T12:58:56.000000Z"},"old":{"doc_number":null,"origin_id":null,"mor_id":null,"doctype_id":null,"user_id":null,"status":null,"date_received":null,"deadline":null,"subject":null,"updated_at":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:58:56',
                'updated_at' => '2022-12-20 20:58:56',
            ),
            59 => 
            array (
                'id' => 60,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 1,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 35,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Forwarded to RD","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:58:56',
                'updated_at' => '2022-12-20 20:58:56',
            ),
            60 => 
            array (
                'id' => 61,
                'log_name' => 'Document',
                'description' => 'created',
                'subject_type' => 'App\\Models\\images',
                'event' => 'created',
                'subject_id' => 1,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 35,
                'properties' => '{"attributes":{"document_id":1,"image_path":"1671541137-sample-pdf.pdf"}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 20:58:57',
                'updated_at' => '2022-12-20 20:58:57',
            ),
            61 => 
            array (
                'id' => 62,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 2,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 35,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 21:45:14',
                'updated_at' => '2022-12-20 21:45:14',
            ),
            62 => 
            array (
                'id' => 63,
                'log_name' => 'Document',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\Document',
                'event' => 'updated',
                'subject_id' => 1,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 35,
                'properties' => '{"attributes":{"memo_number":"test123","updated_at":"2022-12-20T13:45:14.000000Z"},"old":{"memo_number":null,"updated_at":"2022-12-20T12:58:56.000000Z"}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 21:45:14',
                'updated_at' => '2022-12-20 21:45:14',
            ),
            63 => 
            array (
                'id' => 64,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 3,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 21:47:15',
                'updated_at' => '2022-12-20 21:47:15',
            ),
            64 => 
            array (
                'id' => 65,
                'log_name' => 'Document Route',
                'description' => 'deleted',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'deleted',
                'subject_id' => 3,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"old":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 21:48:40',
                'updated_at' => '2022-12-20 21:48:40',
            ),
            65 => 
            array (
                'id' => 66,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 4,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 21:49:46',
                'updated_at' => '2022-12-20 21:49:46',
            ),
            66 => 
            array (
                'id' => 67,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 5,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 35,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 21:52:04',
                'updated_at' => '2022-12-20 21:52:04',
            ),
            67 => 
            array (
                'id' => 68,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 6,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 21:53:50',
                'updated_at' => '2022-12-20 21:53:50',
            ),
            68 => 
            array (
                'id' => 69,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 21:55:58',
                'updated_at' => '2022-12-20 21:55:58',
            ),
            69 => 
            array (
                'id' => 70,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 8,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:00:47',
                'updated_at' => '2022-12-20 22:00:47',
            ),
            70 => 
            array (
                'id' => 71,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 9,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:02:44',
                'updated_at' => '2022-12-20 22:02:44',
            ),
            71 => 
            array (
                'id' => 72,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 10,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:06:24',
                'updated_at' => '2022-12-20 22:06:24',
            ),
            72 => 
            array (
                'id' => 73,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 11,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:07:14',
                'updated_at' => '2022-12-20 22:07:14',
            ),
            73 => 
            array (
                'id' => 74,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 12,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:10:29',
                'updated_at' => '2022-12-20 22:10:29',
            ),
            74 => 
            array (
                'id' => 75,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 13,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:12:04',
                'updated_at' => '2022-12-20 22:12:04',
            ),
            75 => 
            array (
                'id' => 76,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 14,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:14:17',
                'updated_at' => '2022-12-20 22:14:17',
            ),
            76 => 
            array (
                'id' => 77,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 15,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:18:35',
                'updated_at' => '2022-12-20 22:18:35',
            ),
            77 => 
            array (
                'id' => 78,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 16,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:19:48',
                'updated_at' => '2022-12-20 22:19:48',
            ),
            78 => 
            array (
                'id' => 79,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 17,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 3,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:24:15',
                'updated_at' => '2022-12-20 22:24:15',
            ),
            79 => 
            array (
                'id' => 80,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 18,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:24:38',
                'updated_at' => '2022-12-20 22:24:38',
            ),
            80 => 
            array (
                'id' => 81,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 19,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 3,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:27:17',
                'updated_at' => '2022-12-20 22:27:17',
            ),
            81 => 
            array (
                'id' => 82,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 20,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-20 22:27:37',
                'updated_at' => '2022-12-20 22:27:37',
            ),
            82 => 
            array (
                'id' => 83,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 21,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:04:29',
                'updated_at' => '2022-12-21 21:04:29',
            ),
            83 => 
            array (
                'id' => 84,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 22,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:09:08',
                'updated_at' => '2022-12-21 21:09:08',
            ),
            84 => 
            array (
                'id' => 85,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 23,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:12:01',
                'updated_at' => '2022-12-21 21:12:01',
            ),
            85 => 
            array (
                'id' => 86,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 24,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:25:54',
                'updated_at' => '2022-12-21 21:25:54',
            ),
            86 => 
            array (
                'id' => 87,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 25,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:27:32',
                'updated_at' => '2022-12-21 21:27:32',
            ),
            87 => 
            array (
                'id' => 88,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 26,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:30:36',
                'updated_at' => '2022-12-21 21:30:36',
            ),
            88 => 
            array (
                'id' => 89,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 27,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:31:51',
                'updated_at' => '2022-12-21 21:31:51',
            ),
            89 => 
            array (
                'id' => 90,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 28,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:34:26',
                'updated_at' => '2022-12-21 21:34:26',
            ),
            90 => 
            array (
                'id' => 91,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 29,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:37:27',
                'updated_at' => '2022-12-21 21:37:27',
            ),
            91 => 
            array (
                'id' => 92,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 30,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:38:44',
                'updated_at' => '2022-12-21 21:38:44',
            ),
            92 => 
            array (
                'id' => 93,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 31,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:40:26',
                'updated_at' => '2022-12-21 21:40:26',
            ),
            93 => 
            array (
                'id' => 94,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 32,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:42:19',
                'updated_at' => '2022-12-21 21:42:19',
            ),
            94 => 
            array (
                'id' => 95,
                'log_name' => 'Document Route',
                'description' => 'created',
                'subject_type' => 'App\\Models\\DocRoutes',
                'event' => 'created',
                'subject_id' => 33,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"date_received":null,"remarks":"Signed","employee_id":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-21 21:43:43',
                'updated_at' => '2022-12-21 21:43:43',
            ),
            95 => 
            array (
                'id' => 96,
                'log_name' => 'User',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 2,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 1,
                'properties' => '{"attributes":{"name":"Omar Alejandrino","designation":"IT Specialist"},"old":{"name":"Romelmar Alejandrino","designation":null}}',
                'batch_uuid' => NULL,
                'created_at' => '2022-12-25 09:18:05',
                'updated_at' => '2022-12-25 09:18:05',
            ),
        ));
        
        
    }
}